using FogBugzApi;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;

namespace TestApi
{
    //Test project integrating API
    class Program
    {
        static void Main(string[] args)
        {
            //Semi colon seperated fogbugz enviroment variable in the form of domain;user
            var SuperSecretLogin = Environment.GetEnvironmentVariable("Fogbugz").Split(';');
            var Domain = SuperSecretLogin[0];
            var UserName = SuperSecretLogin[1];
            Console.Write("Enter Password:"); var Password = Console.ReadLine();

            //Initialize api and login
            var Api = new FogBugzApiWrapper(Domain, UserName, Password);

            //Get the current filters availiable
            var filters = new List<Filter>(Api.GetFilters());

            //Sets the current filter in the api and the wrapper
            Api.SetCurrentFilter(filters.Find(x => (x.sFilter == "377")));

            //Internally this calls Search("") with an empty query
            var cases = Api.SearchCurrentFilter();

            //Always logoff to invalidate token. It is recommended to reuse the api token as much
            //as possible after its generated by a login. For now we will just logoff.
            Api.Logoff();
        }

    }
}
